### ISSUE TITLE
How to burn firmware for the resc?

### ISSUE THREAD

**Issue by KingQueenWong** [raphaelchang/resc-firmware#6]

**Comment by KingQueenWong** [comment]
I solder two wire with  the pin of PA9 and PA10(STMF405RGT6's USART1).Actually,i select ST's FlashLoader software to burn the firmware.

**Comment by raphaelchang** [comment]
I have two buttons to put the device into bootloader mode, and I use the USB port and dfu-util to upload the compiled binary to the device.
